version: '3.9'
services:
  database:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'production'
    networks:
      - backend
    ports:
      - '5430:5432'
    volumes:
      - database-pg:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql

  storage-service:
    build:
      args:
        progress: plain
      context: ./storage-service
      dockerfile: ./Dockerfile
    networks:
      - backend
    restart: always
    ports:
      #- '127.0.0.1:3000:3000'  доступ к S3 сервису будет только внутри сети docker 
      - '3000:3000'
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  tasks-service:
    build:
      args:
        progress: plain
      context: ./tasks-service
      dockerfile: ./Dockerfile
    depends_on:
      - storage-service
    networks:
      - backend
    restart: always
    ports:
      - '3001:3001'
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  award-service:
    build:
      args:
        progress: plain
      context: ./award-service
      dockerfile: ./Dockerfile
    depends_on:
      - storage-service
    networks:
      - backend
    restart: always
    ports:
      - '3002:3002'
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m

  main-service:
    build:
      args:
        progress: plain
      context: ./main-service
      dockerfile: ./Dockerfile
    depends_on:
      - database
      - storage-service
    networks:
      - backend
    restart: always
    ports:
      - '8080:8080'
      - '8081:8081'
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1024m
        reservations:
          memory: 512m

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

networks:
  backend:
    driver: bridge

volumes:
  database-pg:
